name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: System Setup
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build
        sudo pip3 install setuptools
        sudo pip3 install meson

    - name: Meson Build [static]
      run: |
        meson build -Dc_std=c99 -Dlibrary_type=static

    - name: Compile [static]
      run: |
        ninja -C build

    - name: Run Tests [static]
      run: |
        ninja test -C build

    - name: Meson Build [shared]
      run: |
        meson build -Dc_std=c99 -Dlibrary_type=shared

    - name: Compile [shared]
      run: |
        ninja -C build

    - name: Run Tests [shared]
      run: |
        ninja test -C build
